blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/chikosan/openiptv/tree/main/docs
    about: Check the documentation for answers
  - name: Discussions
    url: https://github.com/chikosan/openiptv/discussions
    about: Ask questions and share ideas
